[package]
name = "wsmux"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
reqwest = "0.12.9"
tokio = { version = "1.42.0", features = ["full"] }
tungstenite = "0.25.0"
